language: rust

sudo: required

rust:
  - 1.20.0
  - stable
  - beta
  - nightly

env:
  global:
  # Improves coverage accuracy
  - RUSTFLAGS="-C link-dead-code"

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - cmake
      - gcc
      - binutils-dev
      - libiberty-dev

before_script:
  - wget https://github.com/Blosc/c-blosc/archive/v1.14.4.tar.gz -O /tmp/c-blosc.tar.gz
  - mkdir c-blosc
  - tar -xv --strip-components=1 -C c-blosc -f /tmp/c-blosc.tar.gz
  - mkdir local
  - mkdir c-blosc/build
  - cd c-blosc/build
  - cmake -DCMAKE_INSTALL_PREFIX=$TRAVIS_BUILD_DIR/local ..
  - cmake --build .
  - cmake --build . --target install
  - export LD_LIBRARY_PATH=$TRAVIS_BUILD_DIR/local/lib:$LD_LIBRARY_PATH
  - export LIBRARY_PATH=$TRAVIS_BUILD_DIR/local/lib:$LIBRARY_PATH

script:
  - cargo build --all --verbose
  - cargo test --all --verbose
  - if [[ "$TRAVIS_RUST_VERSION" == "nightly" ]]; then cargo update -Zminimal-versions && cargo build --all; fi

after_success:
- |
  if [ "$TRAVIS_RUST_VERSION" = "stable" ]; then
    cargo install cargo-kcov &&
    if [ ! -x $HOME/.cargo/bin/kcov ] || [ ! -f $HOME/.cargo/bin/kcov ]; then
      mkdir kcov
      cd kcov
      cargo kcov --print-install-kcov-sh | sh
      cd ${TRAVIS_BUILD_DIR}
      rm -rf kcov
    fi &&
    cargo kcov --all --verbose -- --include-path='blosc/src,blosc-sys/src' &&
    bash <(curl -s https://codecov.io/bash) &&
    echo "CodeCov: uploaded coverage data"
  fi
