language: rust
rust:
  - 1.20.0
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly

before_script:
  - wget https://github.com/Blosc/c-blosc/archive/v1.14.3.tar.gz -O /tmp/c-blosc.tar.gz
  - mkdir c-blosc
  - tar -xv --strip-components=1 -C c-blosc -f /tmp/c-blosc.tar.gz
  - mkdir local
  - mkdir c-blosc/build
  - cd c-blosc/build
  - cmake -DCMAKE_INSTALL_PREFIX=$TRAVIS_BUILD_DIR/local ..
  - cmake --build .
  - cmake --build . --target install
  - export PATH=$TRAVIS_BUILD_DIR/local/lib:$PATH

script:
  - cd blosc
  - cargo build --verbose
  - cargo test --verbose
