[package]
name = "blosc"
version = "0.1.0"
authors = ["Alan Somers <asomers@gmail.com>"]
license = "MIT"
description = """
Rust bindings to the C-BLOSC compression library
"""
categories = ["api-bindings"]
keywords = ["compression"]

[dependencies]
# After posting the first version to crates.io, remove the path dependency and
# rely on the version dependency instead.
blosc-sys = { path = "../blosc-sys" }
#blosc-sys = "1.13.1"
libc = "0.1"

# For official releases, comment out the dependency patch
#[patch.crates-io]
#blosc-sys = { path = "../blosc-sys" }

[dev-dependencies]
bincode = "1.0"
rand = "0.4"
galvanic-test = "0.1.3"
serde = "1.0"
